### ISSUE TITLE
entitie bugs

### ISSUE THREAD

**Issue by seema84** [ChanceSD/AncientGates#19]
Horses (Lamas too) change the color and/or disappear if they move through the portal.

Spigot 1.11
Ancient Gates 2.0.6

**Comment by ChanceSD** [comment]
Yup, this needs to be recoded so they can be transported safely. 
However are you talking about bungee portals or regular ones? I had lamas go through regular ones and they were fine.

**Comment by seema84** [comment]
regular ones no bungee

**Comment by seema84** [comment]
Build #2​1 - if i run "with" horse in a protal

Could not pass event PlayerMoveEvent to AncientGates v2.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:398) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.PacketPlayInVehicleMove.a(SourceFile:48) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.PacketPlayInVehicleMove.a(SourceFile:9) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.UnsupportedOperationException: Not supported.
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
at org.mcteam.ancientgates.util.EntityUtil.setEntityTypeData(EntityUtil.java:189) ~[?:?]
at org.mcteam.ancientgates.util.TeleportUtil.teleportPlayer(TeleportUtil.java:91) ~[?:?]
at org.mcteam.ancientgates.listeners.PluginMovementListener.onPlayerMove(PluginMovementListener.java:104) ~[?:?]
at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-f950f8e-41ade2f]
... 15 more

**Comment by ChanceSD** [comment]
Should be fixed.

**Comment by seema84** [comment]
if i run "with" horse in a protal, the player move to worldspawn and not to the other portal point (the horse works) ... its not fixed

**Comment by seema84** [comment]
can you please fix this bug?

**Comment by seema84** [comment]
player can duplicate horses if they run "on" a horse through a portal ... horses push through the portal works fine but ride through the portal is very defective
